"""Add review_record enriched_classifications audit_document_fk

Revision ID: 68e81369ea6d
Revises: 214922a18f30
Create Date: 2026-09-17 12:45:12.029769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e81369ea6d'
down_revision: Union[str, Sequence[str], None] = '214922a18f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('document_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_audit_logs_document_id', 'audit_logs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('classifications', sa.Column('category', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('section', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('retention_label', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('team_owner', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('classification_type', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('review_reasons', sa.JSON(), nullable=True))
    op.add_column('classifications', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifications', 'updated_at')
    op.drop_column('classifications', 'review_status')
    op.drop_column('classifications', 'review_reasons')
    op.drop_column('classifications', 'classification_type')
    op.drop_column('classifications', 'team_owner')
    op.drop_column('classifications', 'retention_label')
    op.drop_column('classifications', 'document_type')
    op.drop_column('classifications', 'section')
    op.drop_column('classifications', 'category')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_audit_logs_document_id', 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'document_id')
    op.drop_table('review_records')
    # ### end Alembic commands ###
