"""add_human_review_columns_to_classifications

Revision ID: bbb22b7db27d
Revises: e6f7a8b9c0d1
Create Date: 2026-10-09 15:46:48.227914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb22b7db27d'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('classified_by', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('reviewer', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('classifications', sa.Column('review_applied_version', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('review_applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('classifications', sa.Column('ai_proposed_category', sa.String(), nullable=True))
    op.add_column('classifications', sa.Column('ai_confidence_score', sa.Float(), nullable=True))
    op.add_column('classifications', sa.Column('content_changed_after_review', sa.Boolean(), nullable=False, server_default=sa.false()))
    # Remove the server_default after backfill so it doesn't linger in the schema
    op.alter_column('classifications', 'content_changed_after_review', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifications', 'content_changed_after_review')
    op.drop_column('classifications', 'ai_confidence_score')
    op.drop_column('classifications', 'ai_proposed_category')
    op.drop_column('classifications', 'review_applied_at')
    op.drop_column('classifications', 'review_applied_version')
    op.drop_column('classifications', 'reviewed_at')
    op.drop_column('classifications', 'reviewer')
    op.drop_column('classifications', 'classified_by')
    # ### end Alembic commands ###
