"""Add document_number sequence and column to documents table

Revision ID: e6f7a8b9c0d1
Revises: d5e6f7a8b9c0
Create Date: 2026-09-28 16:30:00.000000

What this migration does
------------------------
Introduces a human-friendly sequential document number (101, 102, ...)
so reviewers can refer to documents by a stable, short ID in SharePoint lists.

Schema changes:
  1. CREATE SEQUENCE document_number_seq
       Starts at DOCUMENT_NUMBER_START (default 101). Generates unique integers
       with no gaps risk under concurrent access. Using a SEQUENCE instead of
       max()+1 is the only safe approach when multiple async workers or the
       background poller and a manual trigger run concurrently.

  2. ADD COLUMN document_number INTEGER UNIQUE
       Added to the `documents` table (DocumentRecord). Nullable to support
       existing rows before backfill.

  3. CREATE UNIQUE INDEX ix_documents_document_number

  4. Backfill existing rows (oldest first) using nextval() so they get
       consecutive numbers starting from the sequence's current value.
       Idempotent: only rows where document_number IS NULL are updated.

No existing columns are renamed or removed.
ClassificationRecord can read the number via its relationship to DocumentRecord.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "e6f7a8b9c0d1"
down_revision: Union[str, Sequence[str], None] = "d5e6f7a8b9c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# DOCUMENT_NUMBER_START: first number issued by the sequence.
# IMPORTANT: if you have manually seeded rows already using numbers like 101
# in the SharePoint lists, raise this value above the highest manually used
# number to avoid collisions, then delete or renumber the seeded rows.
DOCUMENT_NUMBER_START = 101


def upgrade() -> None:
    """Apply schema changes."""
    # 1. Create the PostgreSQL sequence
    op.execute(
        sa.text(
            f"CREATE SEQUENCE IF NOT EXISTS document_number_seq "
            f"START WITH {DOCUMENT_NUMBER_START} INCREMENT BY 1 NO CYCLE"
        )
    )

    # 2. Add the column (nullable at first to allow backfilling existing rows)
    op.add_column(
        "documents",
        sa.Column(
            "document_number",
            sa.Integer(),
            nullable=True,
            comment=(
                "Human-friendly sequential document ID (101, 102, ...). "
                "Assigned once when the DocumentRecord is first created. "
                "Never reassigned. Generated by document_number_seq."
            ),
        ),
    )

    # 3. Backfill existing rows in creation order (oldest first).
    #    PostgreSQL UPDATE does not support ORDER BY directly, so we use a
    #    subquery that assigns row numbers ordered by created_at and maps
    #    them to sequence values. Idempotent: only rows where document_number
    #    IS NULL are updated.
    op.execute(
        sa.text(
            """
            WITH ranked AS (
                SELECT id,
                       nextval('document_number_seq') AS new_num
                FROM   documents
                WHERE  document_number IS NULL
                ORDER  BY created_at ASC NULLS LAST
            )
            UPDATE documents
            SET    document_number = ranked.new_num
            FROM   ranked
            WHERE  documents.id = ranked.id
            """
        )
    )

    # 4. Add unique index (now that all existing rows have values)
    op.create_index(
        "ix_documents_document_number",
        "documents",
        ["document_number"],
        unique=True,
    )


def downgrade() -> None:
    """Revert schema changes."""
    op.drop_index("ix_documents_document_number", table_name="documents")
    op.drop_column("documents", "document_number")
    op.execute(sa.text("DROP SEQUENCE IF EXISTS document_number_seq"))
